In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)

In [2]:
df = pd.read_csv('Final_main_exercises_ard.csv')

In [3]:
df

CNTER_NM AGE_NAME GRADE  HE_ht  HE_wt  body_fat  HE_dbp  HE_sbp  \
0           원주       성인   참가증  162.3  61.80      31.1    78.0   119.0   
1           광명       성인   참가증  174.0  63.68      13.0    54.0   109.0   
2           원주       성인   참가증  181.5  74.46      16.2    77.0   117.0   
3           원주       성인   참가증  172.7  62.30      10.4    62.0    99.0   
4           원주       성인   참가증  171.0  71.98      14.9    66.0   120.0   
...        ...      ...   ...    ...    ...       ...     ...     ...   
73752       서초       성인   참가증  171.1  68.00      23.4    76.0   126.0   
73753       서초       성인   참가증  145.9  46.20      30.7    76.0   119.0   
73754       서초       성인   참가증  174.7  59.10       9.4    75.0   123.0   
73755       계룡       성인   2등급  165.5  61.10      27.9    58.0   117.0   
73756       진천       성인   2등급  173.9  60.70      12.1    79.0   134.0   

       l_average  r_average  FLEXIBILITY  HE_BMI  RELATIVE_GRIP  \
0           21.7       24.1         18.5    23.5           38.9   
1           32.6       35.2         16.9    21.0           55.2   
2           43.0       44.7         15.8    22.6           60.0   
3           35.1       36.7          2.4    20.9           58.9   
4           34.4       43.5         -3.4    24.6           60.4   
...          ...        ...          ...     ...            ...   
73752       37.7       37.6         13.6    23.2           55.4   
73753       19.6       21.3          7.5    21.7           46.1   
73754       46.1       45.4         29.1    19.4           78.0   
73755       24.0       29.3         22.3    22.3           48.0   
73756       40.9       42.9         18.7    20.1           70.7   

                                                 PROGRAM  \
0      본운동:넙다리 뒤쪽 스트레칭,상지 루틴 스트레칭,전신 루틴 스트레칭,하지 루틴 스트...   
1      본운동:넙다리 뒤쪽 스트레칭,넙다리 앞쪽 스트레칭,작은 공을 이용한 동적 루틴 스트...   
2      본운동:넙다리 뒤쪽 스트레칭,상지 루틴 스트레칭,전신 루틴 스트레칭,하지 루틴 스트...   
3      본운동:넙다리 뒤쪽 스트레칭,상지 루틴 스트레칭,전신 루틴 스트레칭,하지 루틴 스트...   
4      본운동:넙다리 뒤쪽 스트레칭,상지 루틴 스트레칭,전신 루틴 스트레칭,하지 루틴 스트...   
...                                                  ...   
73752  준비운동:유산소 운동 전 동적 루틴 스트레칭 / 본운동:앉았다 일어서기,의자 앞에서...   
73753  준비운동:유산소 운동 전 동적 루틴 스트레칭 / 본운동:앉았다 일어서기,의자 앞에서...   
73754  준비운동:유산소 운동 전 동적 루틴 스트레칭 / 본운동:앉았다 일어서기,의자 앞에서...   
73755  준비운동:하지 루틴 스트레칭1,상지 루틴 스트레칭 / 본운동:앉았다 일어서기,한발 ...   
73756  준비운동:전신 루틴 스트레칭,유산소 운동 전 동적 루틴 스트레칭,짐볼을 이용한 동적...   

                                               exercises  sex   age  \
0      {'전신루틴스트레칭', '팔벌려뛰기', '엎드려서다리차올리기', '앉았다일어서기',...    2  39.0   
1      {'계단올라갔다내려오기', '앉았다일어서기', '넙다리앞쪽스트레칭', '넙다리뒤쪽스...    1  19.0   
2      {'팔벌려뛰기', '줄넘기', '하지루틴스트레칭1', '실외자전거타기', '전신루틴...    1  25.0   
3      {'전신루틴스트레칭', '무릎높여제자리달리기', '팔벌려뛰기', '엎드려서다리차올리...    1  19.0   
4      {'전신루틴스트레칭', '엎드려서다리차올리기', '앉았다일어서기', '넙다리뒤쪽스트...    1  19.0   
...                                                  ...  ...   ...   
73752  {'네발기기자세로팔다리들기', '누워서엉덩이들어올리기', '앉았다일어서기', '누워...    1  25.0   
73753  {'네발기기자세로팔다리들기', '누워서엉덩이들어올리기', '앉았다일어서기', '누워...    2  21.0   
73754  {'네발기기자세로팔다리들기', '누워서엉덩이들어올리기', '앉았다일어서기', '누워...    1  22.0   
73755  {'계단올라갔다내려오기', '몸통옆으로굽히기', '서서균형잡기', '앉았다일어서기'...    2  23.0   
73756  {'계단올라갔다내려오기', '누워서엉덩이들어올리기', '앉았다일어서기', '엎드려버...    1  20.0   

      depression_scale                MultiLabel  
0                    a                       [1]  
1                    a                       [0]  
2                    a                       [9]  
3                    a                       [9]  
4                    a                       [9]  
...                ...                       ...  
73752                a            [2, 3, 14, 21]  
73753                b            [2, 3, 14, 21]  
73754                b            [2, 3, 14, 21]  
73755                a  [0, 1, 5, 9, 16, 27, 28]  
73756                a  [0, 1, 5, 9, 16, 27, 28]  

[73757 rows x 19 columns]

## 필요없는 feature 제거
transaction number, 지역, 출장여부, 참가자등급, 날짜 .. 등등

In [4]:
# features
df.columns

Index(['CNTER_NM', 'AGE_NAME', 'GRADE', 'HE_ht', 'HE_wt', 'body_fat', 'HE_dbp',
       'HE_sbp', 'l_average', 'r_average', 'FLEXIBILITY', 'HE_BMI',
       'RELATIVE_GRIP', 'PROGRAM', 'exercises', 'sex', 'age',
       'depression_scale', 'MultiLabel'],
      dtype='object')

In [5]:
# Drop columns
df = df.drop(columns = ['CNTER_NM', 'AGE_NAME', 'GRADE', 'PROGRAM', 'exercises'])


# df = df.drop(df.iloc[:,15:],axis = 1)

df

HE_ht  HE_wt  body_fat  HE_dbp  HE_sbp  l_average  r_average  \
0      162.3  61.80      31.1    78.0   119.0       21.7       24.1   
1      174.0  63.68      13.0    54.0   109.0       32.6       35.2   
2      181.5  74.46      16.2    77.0   117.0       43.0       44.7   
3      172.7  62.30      10.4    62.0    99.0       35.1       36.7   
4      171.0  71.98      14.9    66.0   120.0       34.4       43.5   
...      ...    ...       ...     ...     ...        ...        ...   
73752  171.1  68.00      23.4    76.0   126.0       37.7       37.6   
73753  145.9  46.20      30.7    76.0   119.0       19.6       21.3   
73754  174.7  59.10       9.4    75.0   123.0       46.1       45.4   
73755  165.5  61.10      27.9    58.0   117.0       24.0       29.3   
73756  173.9  60.70      12.1    79.0   134.0       40.9       42.9   

       FLEXIBILITY  HE_BMI  RELATIVE_GRIP  sex   age depression_scale  \
0             18.5    23.5           38.9    2  39.0                a   
1             16.9    21.0           55.2    1  19.0                a   
2             15.8    22.6           60.0    1  25.0                a   
3              2.4    20.9           58.9    1  19.0                a   
4             -3.4    24.6           60.4    1  19.0                a   
...            ...     ...            ...  ...   ...              ...   
73752         13.6    23.2           55.4    1  25.0                a   
73753          7.5    21.7           46.1    2  21.0                b   
73754         29.1    19.4           78.0    1  22.0                b   
73755         22.3    22.3           48.0    2  23.0                a   
73756         18.7    20.1           70.7    1  20.0                a   

                     MultiLabel  
0                           [1]  
1                           [0]  
2                           [9]  
3                           [9]  
4                           [9]  
...                         ...  
73752            [2, 3, 14, 21]  
73753            [2, 3, 14, 21]  
73754            [2, 3, 14, 21]  
73755  [0, 1, 5, 9, 16, 27, 28]  
73756  [0, 1, 5, 9, 16, 27, 28]  

[73757 rows x 14 columns]

## Depression scale categorical data -> one-hot encoding

In [6]:
df['depression_scale'].unique()

array(['a', 'b', 'c', 'd'], dtype=object)

In [7]:
df.loc[df['depression_scale'] == 'a', "depression_scale"] = '0'
df.loc[df['depression_scale'] == 'b', "depression_scale"] = '1'
df.loc[df['depression_scale'] == 'c', "depression_scale"] = '2'
df.loc[df['depression_scale'] == 'd', "depression_scale"] = '0'

df

HE_ht  HE_wt  body_fat  HE_dbp  HE_sbp  l_average  r_average  \
0      162.3  61.80      31.1    78.0   119.0       21.7       24.1   
1      174.0  63.68      13.0    54.0   109.0       32.6       35.2   
2      181.5  74.46      16.2    77.0   117.0       43.0       44.7   
3      172.7  62.30      10.4    62.0    99.0       35.1       36.7   
4      171.0  71.98      14.9    66.0   120.0       34.4       43.5   
...      ...    ...       ...     ...     ...        ...        ...   
73752  171.1  68.00      23.4    76.0   126.0       37.7       37.6   
73753  145.9  46.20      30.7    76.0   119.0       19.6       21.3   
73754  174.7  59.10       9.4    75.0   123.0       46.1       45.4   
73755  165.5  61.10      27.9    58.0   117.0       24.0       29.3   
73756  173.9  60.70      12.1    79.0   134.0       40.9       42.9   

       FLEXIBILITY  HE_BMI  RELATIVE_GRIP  sex   age depression_scale  \
0             18.5    23.5           38.9    2  39.0                0   
1             16.9    21.0           55.2    1  19.0                0   
2             15.8    22.6           60.0    1  25.0                0   
3              2.4    20.9           58.9    1  19.0                0   
4             -3.4    24.6           60.4    1  19.0                0   
...            ...     ...            ...  ...   ...              ...   
73752         13.6    23.2           55.4    1  25.0                0   
73753          7.5    21.7           46.1    2  21.0                1   
73754         29.1    19.4           78.0    1  22.0                1   
73755         22.3    22.3           48.0    2  23.0                0   
73756         18.7    20.1           70.7    1  20.0                0   

                     MultiLabel  
0                           [1]  
1                           [0]  
2                           [9]  
3                           [9]  
4                           [9]  
...                         ...  
73752            [2, 3, 14, 21]  
73753            [2, 3, 14, 21]  
73754            [2, 3, 14, 21]  
73755  [0, 1, 5, 9, 16, 27, 28]  
73756  [0, 1, 5, 9, 16, 27, 28]  

[73757 rows x 14 columns]

## Train, Test Set Split

In [8]:
dataset = df.values
dataset

array([[162.3, 61.8, 31.1, ..., 39.0, '0', '[1]'],
       [174.0, 63.68, 13.0, ..., 19.0, '0', '[0]'],
       [181.5, 74.46, 16.2, ..., 25.0, '0', '[9]'],
       ...,
       [174.7, 59.1, 9.4, ..., 22.0, '1', '[2, 3, 14, 21]'],
       [165.5, 61.1, 27.9, ..., 23.0, '0', '[0, 1, 5, 9, 16, 27, 28]'],
       [173.9, 60.7, 12.1, ..., 20.0, '0', '[0, 1, 5, 9, 16, 27, 28]']],
      dtype=object)

In [9]:
from sklearn.model_selection import train_test_split

train_data, test_data = train_test_split(dataset, test_size = 0.2, random_state = 42)
print("훈련 데이터 개수 : ", len(train_data))
print("테스트 데이터 개수 : ", len(test_data))

훈련 데이터 개수 :  59005
테스트 데이터 개수 :  14752


In [10]:
X_train = train_data[:,:13]
Y_train_raw = train_data[:,-1]

In [11]:
# X variables 확인
X_train

array([[173.4, 95.2, 35.4, ..., 1, 17.0, '0'],
       [170.4, 67.0, 22.1, ..., 1, 18.0, '0'],
       [164.6, 52.9, 25.5, ..., 2, 38.0, '0'],
       ...,
       [173.7, 67.1, 17.3, ..., 1, 19.0, '0'],
       [168.5, 70.5, 33.8, ..., 2, 20.0, '0'],
       [148.1, 56.3, 38.7, ..., 2, 41.0, '0']], dtype=object)

# Y 값 Multi-Labeling

In [12]:
df['MultiLabel'].unique()

array(['[1]', '[0]', '[9]', '[28]', '[21]', '[16]', '[2]', '[2, 28]',
       '[14]', '[3, 9]', '[3]', '[0, 2, 3, 21]', '[14, 21]', '[27]',
       '[0, 1, 5, 9, 16, 27, 28]', '[0, 1, 5, 9, 16, 21, 27, 28]',
       '[2, 14, 21]', '[5]', '[2, 21]', '[2, 3]', '[2, 3, 14, 21]',
       '[2, 3, 21]', '[0, 1, 5, 9, 14, 16, 27, 28]', '[12]', '[8, 18]',
       '[0, 1, 2, 3, 5, 9, 16, 21, 27, 28]',
       '[0, 1, 2, 3, 5, 9, 14, 16, 21, 27, 28]', '[0, 2]', '[11]', '[24]',
       '[10]', '[6, 10, 15, 20, 24, 25, 26]', '[2, 3, 21, 28]', '[22]',
       '[20]', '[2, 3, 21, 27]', '[0, 1, 2, 5, 9, 14, 16, 21, 27, 28]',
       '[0, 1, 2, 5, 9, 16, 27, 28]', '[2, 8, 18]', '[19]',
       '[2, 3, 14, 21, 28]', '[2, 14, 21, 27]', '[2, 27]', '[23]',
       '[14, 27]', '[2, 3, 27]', '[26]', '[0, 1, 2, 3, 5, 9, 16, 27, 28]',
       '[21, 28]', '[14, 28]', '[6]',
       '[0, 1, 2, 3, 5, 7, 8, 9, 14, 16, 21, 27, 28]',
       '[6, 10, 15, 20, 22, 24, 25, 26]', '[7, 12, 13, 17, 18, 19, 23]',
       '[11, 14]', '[1

In [13]:
## 운동 묶음 라벨이 81개나 존재. Multi-labeling을 해야함
df['MultiLabel'].nunique()

81

In [14]:
Y_train_raw

array(['[14, 27]', '[6, 10, 15, 20, 22, 24, 25, 26]', '[2, 14, 21]', ...,
       '[4, 7, 8, 11, 12, 13, 17, 18, 19, 23]', '[3]', '[2, 3]'],
      dtype=object)

# Y값이 string list 이기에 int list로 바꿔줌

In [15]:
Y_train_int = []
for each in Y_train_raw:
    each = each.replace('[','')
    each = each.replace(']','')
    temp_list = each.split(',')
    temp_list = [int(x) for x in temp_list] 
    Y_train_int.append(temp_list)

In [16]:
# Y_train_int

In [17]:
from sklearn.preprocessing import MultiLabelBinarizer
mlb = MultiLabelBinarizer()

Y_train = mlb.fit_transform(Y_train_int)
Y_train

array([[0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0]])

### Y 값 인코딩이 제대로 되었는지 확인

In [18]:
## 운동 29개로 라벨링 완료
mlb.classes_

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28])

In [19]:
print("운동 14, 27 을 가지고 있는 라벨이 동일한 binary 값으로 인코딩 되었음")
print(Y_train_int[0])
print(Y_train_int[4])
print(Y_train[0])
print(Y_train[4])

운동 14, 27 을 가지고 있는 라벨이 동일한 binary 값으로 인코딩 되었음
[14, 27]
[14, 27]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0]


In [20]:
import numpy as np

In [21]:
#test set 대상 똑같은 과정 반복
X_test = test_data[:,:13]
Y_test_raw = test_data[:,-1]

In [22]:
X_test

array([[152.7, 52.42, 32.9, ..., 2, 62.0, '0'],
       [159.0, 60.36, 38.9, ..., 2, 55.0, '0'],
       [154.5, 63.1, 36.8, ..., 2, 64.0, '0'],
       ...,
       [168.4, 80.2, 31.3, ..., 1, 25.0, '0'],
       [155.5, 52.9, 37.8, ..., 2, 61.0, '0'],
       [153.0, 44.3, 22.5, ..., 2, 49.0, '2']], dtype=object)

In [23]:
Y_test_raw

array(['[2, 3, 14, 21]', '[2, 3, 21]',
       '[0, 1, 2, 3, 5, 9, 14, 16, 21, 27, 28]', ..., '[2, 3, 21]',
       '[0, 1, 2, 3, 5, 9, 14, 16, 21, 27, 28]', '[2, 3, 14, 21]'],
      dtype=object)

In [24]:
Y_test_int = []
for each in Y_test_raw:
    each = each.replace('[','')
    each = each.replace(']','')
    temp_list = each.split(',')
    temp_list = [int(x) for x in temp_list] 
    Y_test_int.append(temp_list)

In [25]:
Y_test = mlb.fit_transform(Y_test_int)
Y_test

array([[0, 0, 1, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 1, 1],
       ...,
       [0, 0, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 1, 1],
       [0, 0, 1, ..., 0, 0, 0]])

# Decision Tree Model

In [26]:
from sklearn import tree

clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train, Y_train)

## train 시킨 모델에 X값을 하나 입력하면 아래와 같이 운동을 처방해줌
## Binary인코딩한 값을 다시 original label로도 inverse_transform 가능

In [27]:
raw_Y = clf.predict([X_test[0]])
mlb.inverse_transform(raw_Y)

[(4, 7, 8, 11, 12, 13, 17, 18, 19, 23)]

In [28]:
y_pred = clf.predict(X_test)

In [29]:
y_true = Y_test

## Multi-label Confusion Matrix



In [30]:
from sklearn.metrics import multilabel_confusion_matrix
multilabel_confusion_matrix(y_true, y_pred)

array([[[10130,  2118],
        [ 1858,   646]],

       [[ 9680,  2311],
        [ 2001,   760]],

       [[10571,  1717],
        [ 1801,   663]],

       [[10221,  1756],
        [ 1860,   915]],

       [[11028,  1493],
        [ 1412,   819]],

       [[10155,  2111],
        [ 1857,   629]],

       [[11383,  1092],
        [ 1100,  1177]],

       [[10826,  1641],
        [ 1458,   827]],

       [[10412,  1703],
        [ 1599,  1038]],

       [[ 9950,  2170],
        [ 1919,   713]],

       [[11447,  1098],
        [ 1087,  1120]],

       [[10776,  1606],
        [ 1484,   886]],

       [[10912,  1589],
        [ 1435,   816]],

       [[10913,  1588],
        [ 1435,   816]],

       [[10395,  1860],
        [ 1892,   605]],

       [[11449,  1096],
        [ 1087,  1120]],

       [[10131,  2120],
        [ 1865,   636]],

       [[10912,  1588],
        [ 1436,   816]],

       [[10911,  1588],
        [ 1437,   816]],

       [[10885,  1595],
        [ 1445,   827]],



## Classification Report

In [31]:
from sklearn.metrics import classification_report

label_names = ['Exer 0', 'Exer 1', 'Exer 2', 'Exer 3', 'Exer 4', 'Exer 5', 'Exer 6', 'Exer 7', 
               'Exer 8', 'Exer 9', 'Exer 10', 'Exer 11', 'Exer 12','Exer 13','Exer 14','Exer 15',
               'Exer 16 ','Exer 17 ','Exer 18 ','Exer 19 ','Exer 20 ','Exer 21 ','Exer 22 ',
               'Exer 23 ','Exer 24 ','Exer 25 ','Exer 26 ','Exer 27 ','Exer 28 ']

print(classification_report(y_true, y_pred,target_names=label_names))

              precision    recall  f1-score   support

      Exer 0       0.23      0.26      0.25      2504
      Exer 1       0.25      0.28      0.26      2761
      Exer 2       0.28      0.27      0.27      2464
      Exer 3       0.34      0.33      0.34      2775
      Exer 4       0.35      0.37      0.36      2231
      Exer 5       0.23      0.25      0.24      2486
      Exer 6       0.52      0.52      0.52      2277
      Exer 7       0.34      0.36      0.35      2285
      Exer 8       0.38      0.39      0.39      2637
      Exer 9       0.25      0.27      0.26      2632
     Exer 10       0.50      0.51      0.51      2207
     Exer 11       0.36      0.37      0.36      2370
     Exer 12       0.34      0.36      0.35      2251
     Exer 13       0.34      0.36      0.35      2251
     Exer 14       0.25      0.24      0.24      2497
     Exer 15       0.51      0.51      0.51      2207
    Exer 16        0.23      0.25      0.24      2501
    Exer 17        0.34    

/opt/homebrew/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [32]:
from sklearn import metrics
print("Precision for each class: ", metrics.precision_score(y_true, y_pred, average=None))  
print("Accuracy ", metrics.accuracy_score(y_true, y_pred))  

Precision for each class:  [0.23371925 0.24747639 0.27857143 0.34256833 0.35423875 0.22956204
 0.51873072 0.33508914 0.37869391 0.24731183 0.50495942 0.35553772
 0.33929314 0.33943428 0.24543611 0.50541516 0.23076923 0.33943428
 0.33943428 0.34145334 0.50694133 0.26840634 0.54428274 0.33985025
 0.51813019 0.50541516 0.51067616 0.27051246 0.26399491]
Accuracy  0.2214614967462039


In [33]:
## Precision
print("micro: {:.2f}".format(metrics.precision_score(y_true, y_pred, average='micro')))
print("macro: {:.2f} ".format( metrics.precision_score(y_true, y_pred, average='macro')))
print("weighted: {:.2f} ".format( metrics.precision_score(y_true, y_pred, average='weighted')))
print("samples: {:.2f} ".format( metrics.precision_score(y_true, y_pred, average='samples')))  

micro: 0.35
macro: 0.36 
weighted: 0.35 
samples: 0.34 


/opt/homebrew/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
